<?php

namespace Database\Seeders;

use App\Models\Jadwal;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class JadwalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $jadwals = [
            // Monday, 23 June 2025 entries
            [
                'id'           => 2,
                'periode_id'   => 1,
                'judul'        => 'Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 3,
                'periode_id'   => 1,
                'judul'        => 'Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 4,
                'periode_id'   => 1,
                'judul'        => 'Morning Session 3',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 5,
                'periode_id'   => 1,
                'judul'        => 'Morning Session 4',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang D',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 6,
                'periode_id'   => 1,
                'judul'        => 'Morning Session 5',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang E',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 7,
                'periode_id'   => 1,
                'judul'        => 'Morning Session 6',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang F',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 8,
                'periode_id'   => 1,
                'judul'        => 'Morning Session 7',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang G',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 9,
                'periode_id'   => 1,
                'judul'        => 'Afternoon Session 1',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang H',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 10,
                'periode_id'   => 1,
                'judul'        => 'Afternoon Session 2',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang I',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 11,
                'periode_id'   => 1,
                'judul'        => 'Afternoon Session 3',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang J',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 12,
                'periode_id'   => 1,
                'judul'        => 'Afternoon Session 4',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang K',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 13,
                'periode_id'   => 1,
                'judul'        => 'Afternoon Session 5',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-23',
                'end_date'     => '2025-06-24',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang L',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Tuesday, 24 June 2025 entries
            [
                'id'           => 14,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 15,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 16,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Morning Session 3',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 17,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Morning Session 4',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang D',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 18,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Morning Session 5',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang E',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 19,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Morning Session 6',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang F',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 20,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Afternoon Session 1',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang G',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 21,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Afternoon Session 2',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang H',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 22,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Afternoon Session 3',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang I',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 23,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Afternoon Session 4',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang J',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 24,
                'periode_id'   => 1,
                'judul'        => 'Tuesday Afternoon Session 5',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-24',
                'end_date'     => '2025-06-25',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang K',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Wednesday, 25 June 2025 entries
            [
                'id'           => 25,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 26,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 27,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Morning Session 3',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 28,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Morning Session 4',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang D',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 29,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Afternoon Session 1',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang E',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 30,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Afternoon Session 2',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang F',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 31,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Afternoon Session 3',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang G',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 32,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Afternoon Session 4',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang H',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 33,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Afternoon Session 5',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang I',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 34,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Afternoon Session 6',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang J',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 35,
                'periode_id'   => 1,
                'judul'        => 'Wednesday Afternoon Session 7',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-25',
                'end_date'     => '2025-06-26',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang K',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Thursday, 26 June 2025 entries
            [
                'id'           => 36,
                'periode_id'   => 1,
                'judul'        => 'Thursday Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 37,
                'periode_id'   => 1,
                'judul'        => 'Thursday Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 38,
                'periode_id'   => 1,
                'judul'        => 'Thursday Morning Session 3',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 39,
                'periode_id'   => 1,
                'judul'        => 'Thursday Morning Session 4',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang D',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 40,
                'periode_id'   => 1,
                'judul'        => 'Thursday Morning Session 5',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang E',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 41,
                'periode_id'   => 1,
                'judul'        => 'Thursday Morning Session 6',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang F',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 42,
                'periode_id'   => 1,
                'judul'        => 'Thursday Afternoon Session 1',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang G',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 43,
                'periode_id'   => 1,
                'judul'        => 'Thursday Afternoon Session 2',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang H',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 44,
                'periode_id'   => 1,
                'judul'        => 'Thursday Afternoon Session 3',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang I',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 45,
                'periode_id'   => 1,
                'judul'        => 'Thursday Afternoon Session 4',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang J',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 46,
                'periode_id'   => 1,
                'judul'        => 'Thursday Afternoon Session 5',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang K',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 47,
                'periode_id'   => 1,
                'judul'        => 'Thursday Afternoon Session 6',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang L',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 48,
                'periode_id'   => 1,
                'judul'        => 'Thursday Afternoon Session 7',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-26',
                'end_date'     => '2025-06-27',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang M',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Monday, 30 June 2025 entries
            [
                'id'           => 49,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 50,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 51,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Morning Session 3',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 52,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Morning Session 4',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang D',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 53,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Morning Session 5',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang E',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 54,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Morning Session 6',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang F',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 55,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Afternoon Session 1',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang G',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 56,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Afternoon Session 2',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang H',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 57,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Afternoon Session 3',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang I',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 58,
                'periode_id'   => 1,
                'judul'        => 'Monday Week 2 Afternoon Session 4',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-06-30',
                'end_date'     => '2025-07-07',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang J',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Tuesday, 1 July 2025 entries
            [
                'id'           => 59,
                'periode_id'   => 1,
                'judul'        => 'Tuesday July Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-07-01',
                'end_date'     => '2025-07-08',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 60,
                'periode_id'   => 1,
                'judul'        => 'Tuesday July Afternoon Session 1',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-07-01',
                'end_date'     => '2025-07-08',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
	    [
                'id'           => 61,
                'periode_id'   => 1,
                'judul'        => 'Tuesday July Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-07-01',
                'end_date'     => '2025-07-08',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Wednesday, 2 July 2025 entries
            [
                'id'           => 62,
                'periode_id'   => 1,
                'judul'        => 'Wednesday July Afternoon Session 1',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-07-02',
                'end_date'     => '2025-07-09',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 63,
                'periode_id'   => 1,
                'judul'        => 'Wednesday July Afternoon Session 2',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-07-02',
                'end_date'     => '2025-07-09',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 64,
                'periode_id'   => 1,
                'judul'        => 'Wednesday July Afternoon Session 3',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-07-02',
                'end_date'     => '2025-07-09',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 65,
                'periode_id'   => 1,
                'judul'        => 'Wednesday July Afternoon Session 4',
                'deskripsi'    => 'Afternoon activity session',
                'start_date'   => '2025-07-02',
                'end_date'     => '2025-07-09',
                'start_time'   => '13:00:00',
                'end_time'     => '16:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang D',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Thursday, 3 July 2025 entries
            [
                'id'           => 66,
                'periode_id'   => 1,
                'judul'        => 'Thursday July Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-07-03',
                'end_date'     => '2025-07-10',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 67,
                'periode_id'   => 1,
                'judul'        => 'Thursday July Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-07-03',
                'end_date'     => '2025-07-10',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],

            // Friday, 4 July 2025 entries
            [
                'id'           => 68,
                'periode_id'   => 1,
                'judul'        => 'Friday July Morning Session 1',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-07-04',
                'end_date'     => '2025-07-11',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang A',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 69,
                'periode_id'   => 1,
                'judul'        => 'Friday July Morning Session 2',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-07-04',
                'end_date'     => '2025-07-11',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang B',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 70,
                'periode_id'   => 1,
                'judul'        => 'Friday July Morning Session 3',
                'deskripsi'    => 'Morning activity session',
                'start_date'   => '2025-07-04',
                'end_date'     => '2025-07-11',
                'start_time'   => '08:00:00',
                'end_time'     => '11:00:00',
                'is_all_day'   => 0,
                'is_active'    => true,
                'type'         => 'lainnya',
                'priority'     => 'rendah',
                'location'     => 'Ruang C',
                'meeting_link' => null,
                'status'       => 'validated',
                'created_by'   => 1,

                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ];

        Jadwal::insert($jadwals);
    }
}    
